"""add child_staff table

Revision ID: 10c3116c2560
Revises: 
Create Date: 2025-07-11 21:18:40.534659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c3116c2560'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child_activity_participation', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'activities', ['activity_id'], ['id'])

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'daycares', ['daycare_id'], ['id'])

    with op.batch_alter_table('daycare_staff', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'daycares', ['daycare_id'], ['id'])

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'daycares', ['daycare_id'], ['id'])

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'invoices', ['invoice_id'], ['id'])

    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'daycares', ['daycare_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'invoices', ['invoice_id'], ['id'])

    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'daycares', ['daycare_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('daycare_staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('child_activity_participation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
