"""Add age_groups table and FK to children

Revision ID: b0866bf9e5d2
Revises: 10c3116c2560
Create Date: 2025-07-12 20:15:48.753583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0866bf9e5d2'
down_revision = '10c3116c2560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_children_age_group', ['age_group_id'], unique=False)
        batch_op.create_foreign_key(None, 'age_groups', ['age_group_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_age_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'age_groups', ['requested_age_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('requested_age_group_id')

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_children_age_group')
        batch_op.drop_column('age_group_id')

    # ### end Alembic commands ###
